/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Footer: typeof import('./src/components/ui/footer/Footer.vue')['default']
    Header: typeof import('./src/components/ui/header/Header.vue')['default']
    HomeHeadline: typeof import('./src/components/views/home/HomeHeadline.vue')['default']
    HomeTrending: typeof import('./src/components/views/home/HomeTrending.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Trending: typeof import('./src/components/views/home/Trending.vue')['default']
  }
}
